
// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Jun 18 2023 14:54:20 -03 (Jun 18 2023 17:54:20 UTC)

// Verification Directory fv/i2c_master 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  LSGCPHDX0 RC_CGIC_INST(.E (enable), .CLK (ck_in), .SE (test), .GCLK
       (ck_out));
endmodule

module i2c_master(clk, reset, start, stop, rw, addr, w_data, i2c_scl,
     i2c_sda);
  input clk, reset, start, stop, rw;
  input [6:0] addr;
  input [7:0] w_data;
  output i2c_scl;
  inout i2c_sda;
  wire clk, reset, start, stop, rw;
  wire [6:0] addr;
  wire [7:0] w_data;
  wire i2c_scl;
  wire i2c_sda;
  wire [3:0] current;
  wire [7:0] count;
  wire [3:0] next;
  wire i2c_scl_enable, logic_0_1_net, logic_0_2_net, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_61, n_62, n_64, n_65;
  wire n_85, n_86, n_92, rc_gclk, rc_gclk_603;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_85), .ck_in (clk), .ck_out
       (rc_gclk), .test (logic_0_1_net));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_86), .ck_in (clk), .ck_out
       (rc_gclk_603), .test (logic_0_2_net));
  NO22HDX0 g1273__2398(.A (n_65), .B (n_57), .C (reset), .Q
       (i2c_scl_enable));
  NO2I1HDX1 g1274__5107(.AN (current[3]), .B (current[0]), .Q (n_57));
  OR2HDX1 g1275__6260(.A (current[1]), .B (current[2]), .Q (n_65));
  NA3I2HDX1 g1644__4319(.AN (n_56), .BN (n_53), .C (n_55), .Q
       (i2c_sda));
  ON221HDX0 g1645__8428(.A (n_44), .B (n_34), .C (n_16), .D (n_49), .E
       (n_54), .Q (n_56));
  ON32HDX0 g1646__5526(.A (current[0]), .B (n_16), .C (n_31), .D
       (n_13), .E (n_52), .Q (n_85));
  AN33HDX1 g1647__6783(.A (count[1]), .B (n_9), .C (n_43), .D
       (count[2]), .E (n_28), .F (n_50), .Q (n_55));
  AN321HDX0 g1648__3680(.A (count[2]), .B (n_38), .C (n_32), .D
       (i2c_sda), .E (n_33), .F (n_36), .Q (n_54));
  AO22HDX1 g1649__1617(.A (n_47), .B (n_28), .C (n_46), .D (n_32), .Q
       (n_53));
  DFRQHDX1 next_reg_1(.C (rc_gclk_603), .D (n_51), .Q (next[1]));
  DFRQHDX1 next_reg_0(.C (rc_gclk_603), .D (n_48), .Q (next[0]));
  AN21HDX1 g1652__2802(.A (n_40), .B (current[2]), .C (n_20), .Q
       (n_52));
  AO211HDX0 g1653__1705(.A (n_20), .B (n_8), .C (n_33), .D (n_45), .Q
       (n_86));
  ON211HDX0 g1654__5122(.A (current[1]), .B (n_62), .C (n_37), .D
       (n_30), .Q (n_51));
  DFRQHDX1 next_reg_2(.C (rc_gclk_603), .D (n_42), .Q (next[2]));
  DFRQHDX1 next_reg_3(.C (rc_gclk_603), .D (n_39), .Q (next[3]));
  AO321HDX0 g1657__8246(.A (w_data[7]), .B (count[0]), .C (count[1]),
       .D (w_data[5]), .E (n_21), .F (n_29), .Q (n_50));
  AN21HDX1 g1658__7098(.A (n_20), .B (rw), .C (n_35), .Q (n_49));
  ON211HDX0 g1659__6131(.A (rw), .B (n_17), .C (n_41), .D (n_62), .Q
       (n_48));
  NA22HDX1 g1660__1881(.A (n_31), .B (w_data[0]), .C (n_23), .Q (n_47));
  NA22HDX1 g1661__5115(.A (n_31), .B (addr[0]), .C (n_24), .Q (n_46));
  ON211HDX0 g1662__7482(.A (n_34), .B (n_25), .C (n_26), .D (n_65), .Q
       (n_45));
  AN22HDX1 g1663__4733(.A (n_28), .B (w_data[1]), .C (n_32), .D
       (addr[1]), .Q (n_44));
  AO22HDX1 g1664__6161(.A (n_28), .B (n_27), .C (n_32), .D (n_22), .Q
       (n_43));
  NA22HDX1 g1665__9315(.A (n_20), .B (current[1]), .C (n_17), .Q
       (n_42));
  ON21HDX1 g1666__9945(.A (n_13), .B (start), .C (n_19), .Q (n_41));
  NA2HDX1 g1667__2883(.A (n_31), .B (current[0]), .Q (n_40));
  ON32HDX0 g1668__2346(.A (current[1]), .B (n_8), .C (current[0]), .D
       (n_7), .E (n_11), .Q (n_39));
  AO22HDX0 g1669__1666(.A (addr[4]), .B (n_15), .C (n_21), .D
       (addr[5]), .Q (n_38));
  AN22HDX1 g1670__7410(.A (n_12), .B (current[0]), .C (n_19), .D
       (current[1]), .Q (n_37));
  ON22HDX0 g1671__6417(.A (current[1]), .B (n_18), .C (n_8), .D (n_65),
       .Q (n_36));
  AO32HDX1 g1672__5477(.A (i2c_sda), .B (current[2]), .C (n_10), .D
       (i2c_sda), .E (n_14), .Q (n_35));
  NA2I1HDX1 g1674__2398(.AN (n_17), .B (rw), .Q (n_30));
  AND2HDX1 g1675__5107(.A (n_15), .B (w_data[4]), .Q (n_29));
  NA2I1HDX1 g1676__6260(.AN (count[2]), .B (n_21), .Q (n_34));
  NO2HDX1 g1677__4319(.A (n_13), .B (current[0]), .Q (n_33));
  AND2HDX1 g1678__8428(.A (n_19), .B (n_8), .Q (n_32));
  NO2HDX1 g1679__5526(.A (n_64), .B (count[2]), .Q (n_31));
  MU2HDX0 g1680__6783(.IN0 (w_data[2]), .IN1 (w_data[6]), .S
       (count[2]), .Q (n_27));
  NA3I1HDX1 g1681__3680(.AN (n_16), .B (current[0]), .C (stop), .Q
       (n_26));
  AN21HDX1 g1682__1617(.A (n_10), .B (n_8), .C (n_12), .Q (n_25));
  NA3I2HDX1 g1683__2802(.AN (n_61), .BN (count[2]), .C (addr[3]), .Q
       (n_24));
  NA3I2HDX1 g1684__1705(.AN (n_61), .BN (count[2]), .C (w_data[3]), .Q
       (n_23));
  MU2HDX0 g1685__5122(.IN0 (addr[2]), .IN1 (addr[6]), .S (count[2]), .Q
       (n_22));
  NO2HDX1 g1686__8246(.A (n_62), .B (n_13), .Q (n_28));
  INHDX1 g1687(.A (n_19), .Q (n_18));
  NA2HDX1 g1688__7098(.A (i2c_scl_enable), .B (clk), .Q (i2c_scl));
  NO2HDX1 g1689__6131(.A (n_9), .B (count[1]), .Q (n_21));
  NA2HDX1 g1690__1881(.A (count[0]), .B (count[1]), .Q (n_61));
  NO2HDX1 g1691__5115(.A (n_10), .B (current[2]), .Q (n_20));
  NO2HDX1 g1692__7482(.A (current[0]), .B (current[2]), .Q (n_19));
  INHDX1 g1693(.A (n_15), .Q (n_64));
  INHDX1 g1694(.A (n_62), .Q (n_14));
  INHDX1 g1695(.A (n_13), .Q (n_12));
  NA2HDX1 g1696__4733(.A (current[2]), .B (n_7), .Q (n_17));
  NA2HDX1 g1697__6161(.A (n_8), .B (current[1]), .Q (n_16));
  NO2HDX1 g1698__9315(.A (count[0]), .B (count[1]), .Q (n_15));
  NA2HDX1 g1699__9945(.A (current[0]), .B (current[2]), .Q (n_62));
  NA2HDX1 g1700__2883(.A (n_7), .B (n_8), .Q (n_13));
  DFRQHDX1 count_reg_2(.C (rc_gclk), .D (n_92), .Q (count[2]));
  DFRQHDX1 count_reg_1(.C (rc_gclk), .D (n_5), .Q (count[1]));
  NA3HDX1 g1296__1666(.A (n_3), .B (n_64), .C (n_61), .Q (n_5));
  ON22HDX0 g1297__7410(.A (current[1]), .B (current[0]), .C (count[0]),
       .D (n_1), .Q (n_4));
  NA2HDX1 g1302__6417(.A (n_64), .B (count[2]), .Q (n_2));
  NA2I1HDX1 g1303__5477(.AN (current[1]), .B (n_62), .Q (n_3));
  INHDX1 g1304(.A (n_65), .Q (n_1));
  INHDX1 g1305(.A (reset), .Q (n_0));
  DFRRHDX1 current_reg_2(.RN (n_0), .C (clk), .D (next[2]), .Q
       (current[2]), .QN (n_11));
  DFRRHDX1 current_reg_0(.RN (n_0), .C (clk), .D (next[0]), .Q
       (current[0]), .QN (n_10));
  DFRHDX1 count_reg_0(.C (rc_gclk), .D (n_4), .Q (count[0]), .QN (n_9));
  DFRRHDX1 current_reg_3(.RN (n_0), .C (clk), .D (next[3]), .Q
       (current[3]), .QN (n_8));
  DFRRHDX1 current_reg_1(.RN (n_0), .C (clk), .D (next[1]), .Q
       (current[1]), .QN (n_7));
  NA3I1HDX1 g2(.AN (n_31), .B (n_3), .C (n_2), .Q (n_92));
  LOGIC0HD tie_0_cell(.Q (logic_0_1_net));
  LOGIC0HD tie_0_cell1(.Q (logic_0_2_net));
endmodule

